In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('customers.csv')

In [3]:
df.head(2)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/

In [4]:
df.tail(2)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [5]:
df.describe()

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

In [8]:
df.dtypes

Index                 int64
Customer Id          object
First Name           object
Last Name            object
Company              object
City                 object
Country              object
Phone 1              object
Phone 2              object
Email                object
Subscription Date    object
Website              object
dtype: object

In [12]:
df.isnull()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False,False,False,False

In [13]:
df.isnull().any()

Index                False
Customer Id          False
First Name           False
Last Name            False
Company              False
City                 False
Country              False
Phone 1              False
Phone 2              False
Email                False
Subscription Date    False
Website              False
dtype: bool

In [14]:
df.isnull().sum()

Index                0
Customer Id          0
First Name           0
Last Name            0
Company              0
City                 0
Country              0
Phone 1              0
Phone 2              0
Email                0
Subscription Date    0
Website              0
dtype: int64

In [15]:
df2=pd.read_csv('food.csv')
df2.isnull().any()

Country           False
Real coffee       False
Instant coffee    False
Tea               False
Sweetener          True
Biscuits           True
Powder soup       False
Tin soup          False
Potatoes          False
Frozen fish       False
Frozen veggies    False
Apples            False
Oranges           False
Tinned fruit      False
Jam               False
Garlic            False
Butter            False
Margarine         False
Olive oil         False
Yoghurt            True
Crisp bread       False
dtype: bool

In [16]:
df2.isnull().sum()

Country           0
Real coffee       0
Instant coffee    0
Tea               0
Sweetener         1
Biscuits          1
Powder soup       0
Tin soup          0
Potatoes          0
Frozen fish       0
Frozen veggies    0
Apples            0
Oranges           0
Tinned fruit      0
Jam               0
Garlic            0
Butter            0
Margarine         0
Olive oil         0
Yoghurt           1
Crisp bread       0
dtype: int64

In [17]:
# filled dataset
df_filled=df2.fillna(0)
df_filled.isnull().sum()

Country           0
Real coffee       0
Instant coffee    0
Tea               0
Sweetener         0
Biscuits          0
Powder soup       0
Tin soup          0
Potatoes          0
Frozen fish       0
Frozen veggies    0
Apples            0
Oranges           0
Tinned fruit      0
Jam               0
Garlic            0
Butter            0
Margarine         0
Olive oil         0
Yoghurt           0
Crisp bread       0
dtype: int64

In [18]:
df2.isnull().sum()

Country           0
Real coffee       0
Instant coffee    0
Tea               0
Sweetener         1
Biscuits          1
Powder soup       0
Tin soup          0
Potatoes          0
Frozen fish       0
Frozen veggies    0
Apples            0
Oranges           0
Tinned fruit      0
Jam               0
Garlic            0
Butter            0
Margarine         0
Olive oil         0
Yoghurt           1
Crisp bread       0
dtype: int64

In [20]:
df2['Yoghurt']=df2['Yoghurt'].fillna(df2['Yoghurt'].mean())
df2.isnull().sum()

Country           0
Real coffee       0
Instant coffee    0
Tea               0
Sweetener         1
Biscuits          1
Powder soup       0
Tin soup          0
Potatoes          0
Frozen fish       0
Frozen veggies    0
Apples            0
Oranges           0
Tinned fruit      0
Jam               0
Garlic            0
Butter            0
Margarine         0
Olive oil         0
Yoghurt           0
Crisp bread       0
dtype: int64

In [24]:
df2['Biscuits']=df2['Biscuits'].fillna(df2['Biscuits'].mean())
df2['Sweetener']=df2['Sweetener'].fillna(df2['Sweetener'].median())

In [26]:
df2.isnull().sum()

Country           0
Real coffee       0
Instant coffee    0
Tea               0
Sweetener         0
Biscuits          0
Powder soup       0
Tin soup          0
Potatoes          0
Frozen fish       0
Frozen veggies    0
Apples            0
Oranges           0
Tinned fruit      0
Jam               0
Garlic            0
Butter            0
Margarine         0
Olive oil         0
Yoghurt           0
Crisp bread       0
dtype: int64

# Renaming columns

In [32]:
df_renamed=df2.rename({'Frozen fish	':"Fish"},axis=1)

In [33]:
df2.head()

,Country,Real coffee,Instant coffee,Tea,Sweetener,Biscuits,Powder soup,Tin soup,Potatoes,Frozen fish,...,Apples,Oranges,Tinned fruit,Jam,Garlic,Butter,Margarine,Olive oil,Yoghurt,Crisp bread
0,Germany,90,49,88,19.0,57.0,51,19,21,27,...,81,75,44,71,22,91,85,74,30.0,26
1,Italy,82,10,60,2.0,55.0,41,3,2,4,...,67,71,9,46,80,66,24,94,5.0,18
2,France,88,42,63,4.0,76.0,53,11,23,11,...,87,84,40,45,88,94,47,36,57.0,3
3,Holland,96,62,98,32.0,62.0,67,43,7,14,...,83,89,61,81,15,31,97,13,53.0,15
4,Belgium,94,38,48,11.0,74.0,37,23,9,13,...,76,76,42,57,29,84,80,83,20.0,5

In [35]:
df2['Real coffee'].dtype

dtype('int64')

In [39]:
# Convert this into float 
df2['New coffee']=df2['Real coffee'].astype(float)
df2.head(2)

,Country,Real coffee,Instant coffee,Tea,Sweetener,Biscuits,Powder soup,Tin soup,Potatoes,Frozen fish,...,Oranges,Tinned fruit,Jam,Garlic,Butter,Margarine,Olive oil,Yoghurt,Crisp bread,New coffee
0,Germany,90,49,88,19.0,57.0,51,19,21,27,...,75,44,71,22,91,85,74,30.0,26,90.0
1,Italy,82,10,60,2.0,55.0,41,3,2,4,...,71,9,46,80,66,24,94,5.0,18,82.0

In [44]:
# applying a function
df2['Frozen fish new']=df2['Frozen fish'].apply(lambda x : x >30)
df2.head()

,Country,Real coffee,Instant coffee,Tea,Sweetener,Biscuits,Powder soup,Tin soup,Potatoes,Frozen fish,...,Jam,Garlic,Butter,Margarine,Olive oil,Yoghurt,Crisp bread,New coffee,Frozen fish new,Frozen fish new
0,Germany,90,49,88,19.0,57.0,51,19,21,27,...,71,22,91,85,74,30.0,26,90.0,False,False
1,Italy,82,10,60,2.0,55.0,41,3,2,4,...,46,80,66,24,94,5.0,18,82.0,False,False
2,France,88,42,63,4.0,76.0,53,11,23,11,...,45,88,94,47,36,57.0,3,88.0,False,False
3,Holland,96,62,98,32.0,62.0,67,43,7,14,...,81,15,31,97,13,53.0,15,96.0,False,False
4,Belgium,94,38,48,11.0,74.0,37,23,9,13,...,57,29,84,80,83,20.0,5,94.0,False,False

In [59]:
df2[df2['Real coffee']<=31]

,Country,Real coffee,Instant coffee,Tea,Sweetener,Biscuits,Powder soup,Tin soup,Potatoes,Frozen fish,...,Jam,Garlic,Butter,Margarine,Olive oil,Yoghurt,Crisp bread,New coffee,Frozen fish new,Frozen fish new
6,England,27,86,99,22.0,91.0,55,76,17,20,...,91,11,95,94,57,11.0,28,27.0,False,False
15,Ireland,30,52,99,11.0,80.0,75,18,2,5,...,89,5,97,25,31,3.0,9,30.0,False,False

# Aggregation and Grouping

In [61]:
grouped_mean=df2.groupby('Country')['Tea'].mean()
grouped_mean

Country
Austria        61.0
Belgium        48.0
Denmark        92.0
England        99.0
Finland        84.0
France         63.0
Germany        88.0
Holland        98.0
Ireland        99.0
Italy          60.0
Luxembourg     86.0
Norway         83.0
Portugal       77.0
Spain          40.0
Sweden         93.0
Switzerland    85.0
Name: Tea, dtype: float64

In [62]:
grouped_sum=df2.groupby(['Country','Frozen fish new'])['Tea'].sum()
grouped_sum

Country      Frozen fish new
Austria      False              61
Belgium      False              48
Denmark      True               92
England      False              99
Finland      False              84
France       False              63
Germany      False              88
Holland      False              98
Ireland      False              99
Italy        False              60
Luxembourg   False              86
Norway       False              83
Portugal     False              77
Spain        False              40
Sweden       True               93
Switzerland  False              85
Name: Tea, dtype: int64